apiVersion: v1
kind: Pod
metadata:
  name: aspnetapp
  labels:
    app: aspnetapp
spec:
  containers:
  - image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
    name: aspnetapp-image
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: aspnetapp
spec:
  selector:
    app: aspnetapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: aspnetapp
  annotations:
    artifact.spinnaker.io/location: default
    artifact.spinnaker.io/name: aspnetapp
    artifact.spinnaker.io/type: kubernetes/replicaSet
    artifact.spinnaker.io/version: v000
    moniker.spinnaker.io/application: aspnetapp
    moniker.spinnaker.io/cluster: replicaSet aspnetapp
    moniker.spinnaker.io/sequence: '0'
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service aspnetapp"]'
  labels:
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: aspnetapp
    tier: aspnetapp
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: aspnetapp
  template:
    metadata:
      annotations:
        artifact.spinnaker.io/location: default
        artifact.spinnaker.io/name: aspnetapp
        artifact.spinnaker.io/type: kubernetes/replicaSet
        artifact.spinnaker.io/version: v000
        moniker.spinnaker.io/application: aspnetapp
        moniker.spinnaker.io/cluster: replicaSet aspnetapp
        moniker.spinnaker.io/sequence: '0'
      labels:
        app: aspnetapp
        app.kubernetes.io/name: aspnetapp
        tier: aspnetapp
    spec:
      containers:
        - image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
          imagePullPolicy: IfNotPresent
          name: aspnetapp
          ports:
            - containerPort: 6000

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aspnetapp
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: aspnetapp
          servicePort: 80
